<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Don't access directly
};

/**
 * The list of predefined languages
 * For WordPress locales, see https://translate.wordpress.org/
 * For W3C locales, see http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
 * See also #33511
 * Facebook locales used to be available at https://www.facebook.com/translations/FacebookLocales.xml
 *
 * For each language:
 * [code]     => ISO 639-1 language code
 * [locale]   => WordPress locale
 * [name]     => name
 * [dir]      => text direction
 * [flag]     => flag code
 * [w3c]      => W3C locale
 * [facebook] => Facebook locale
 *
 * Facebook locales without equivalent WordPress locale:
 * 'ay_BO' (Aymara)
 * 'ck_US' (Cherokee)
 * 'en_IN' (English India)
 * 'gx_GR' (Classical Greek)
 * 'ig_NG' (Igbo)
 * 'ja_KS' (Japanese Kansai)
 * 'lg_UG' (Ganda)
 * 'nd_ZW' (Ndebele)
 * 'ny_MW' (Chewa)
 * 'qu_PE' (Quechua)
 * 'se_NO' (Northern Sami)
 * 'tl_ST' (Klingon)
 * 'wo_SN' (Wolof)
 * 'yi_DE' (Yiddish)
 * 'zu_ZA' (Zulu)
 * 'zz_TR' (Zazaki)
 */
$languages = [
	'af' => [
		'code'     => 'af',
		'locale'   => 'af',
		'name'     => 'Afrikaans',
		'dir'      => 'ltr',
		'flag'     => 'za',
		'facebook' => 'af_ZA',
	],
	'ak' => [
		'facebook' => 'ak_GH',
	],
	'am' => [
		'facebook' => 'am_ET',
	],
	'ar' => [
		'code'     => 'ar',
		'locale'   => 'ar',
		'name'     => 'العربية',
		'dir'      => 'rtl',
		'flag'     => 'arab',
		'facebook' => 'ar_AR',
	],
	'arq' => [
		'facebook' => 'ar_AR',
	],
	'ary' => [
		'code'     => 'ar',
		'locale'   => 'ary',
		'name'     => 'العربية المغربية',
		'dir'      => 'rtl',
		'flag'     => 'ma',
		'facebook' => 'ar_AR',
	],
	'as' => [
		'code'     => 'as',
		'locale'   => 'as',
		'name'     => 'অসমীয়া',
		'dir'      => 'ltr',
		'flag'     => 'in',
		'facebook' => 'as_IN',
	],
	'az' => [
		'code'     => 'az',
		'locale'   => 'az',
		'name'     => 'Azərbaycan',
		'dir'      => 'ltr',
		'flag'     => 'az',
		'facebook' => 'az_AZ',
	],
	'azb' => [
		'code'     => 'az',
		'locale'   => 'azb',
		'name'     => 'گؤنئی آذربایجان',
		'dir'      => 'rtl',
		'flag'     => 'az',
	],
	'bel' => [
		'code'     => 'be',
		'locale'   => 'bel',
		'name'     => 'Беларуская мова',
		'dir'      => 'ltr',
		'flag'     => 'by',
		'w3c'      => 'be',
		'facebook' => 'be_BY',
	],
	'bg_BG' => [
		'code'     => 'bg',
		'locale'   => 'bg_BG',
		'name'     => 'български',
		'dir'      => 'ltr',
		'flag'     => 'bg',
		'facebook' => 'bg_BG',
	],
	'bn_BD' => [
		'code'     => 'bn',
		'locale'   => 'bn_BD',
		'name'     => 'বাংলা',
		'dir'      => 'ltr',
		'flag'     => 'bd',
		'facebook' => 'bn_IN',
	],
	'bo' => [
		'code'     => 'bo',
		'locale'   => 'bo',
		'name'     => 'བོད་ཡིག',
		'dir'      => 'ltr',
		'flag'     => 'tibet',
	],
	'bre' => [
		'w3c'      => 'br',
		'facebook' => 'br_FR',
	],
	'bs_BA' => [
		'code'     => 'bs',
		'locale'   => 'bs_BA',
		'name'     => 'Bosanski',
		'dir'      => 'ltr',
		'flag'     => 'ba',
		'facebook' => 'bs_BA',
	],
	'ca' => [
		'code'     => 'ca',
		'locale'   => 'ca',
		'name'     => 'Català',
		'dir'      => 'ltr',
		'flag'     => 'catalonia',
		'facebook' => 'ca_ES',
	],
	'ceb' => [
		'code'     => 'ceb',
		'locale'   => 'ceb',
		'name'     => 'Cebuano',
		'dir'      => 'ltr',
		'flag'     => 'ph',
		'facebook' => 'cx_PH',
	],
	'ckb' => [
		'code'     => 'ku',
		'locale'   => 'ckb',
		'name'     => 'کوردی',
		'dir'      => 'rtl',
		'flag'     => 'kurdistan',
		'facebook' => 'cb_IQ',
	],
	'co' => [
		'facebook' => 'co_FR',
	],
	'cs_CZ' => [
		'code'     => 'cs',
		'locale'   => 'cs_CZ',
		'name'     => 'Čeština',
		'dir'      => 'ltr',
		'flag'     => 'cz',
		'facebook' => 'cs_CZ',
	],
	'cy' => [
		'code'     => 'cy',
		'locale'   => 'cy',
		'name'     => 'Cymraeg',
		'dir'      => 'ltr',
		'flag'     => 'wales',
		'facebook' => 'cy_GB',
	],
	'da_DK' => [
		'code'     => 'da',
		'locale'   => 'da_DK',
		'name'     => 'Dansk',
		'dir'      => 'ltr',
		'flag'     => 'dk',
		'facebook' => 'da_DK',
	],
	'de_CH' => [
		'code'     => 'de',
		'locale'   => 'de_CH',
		'name'     => 'Deutsch',
		'dir'      => 'ltr',
		'flag'     => 'ch',
		'facebook' => 'de_DE',
	],
	'de_CH_informal' => [
		'code'     => 'de',
		'locale'   => 'de_CH_informal',
		'name'     => 'Deutsch',
		'dir'      => 'ltr',
		'flag'     => 'ch',
		'w3c'      => 'de-CH',
		'facebook' => 'de_DE',
	],
	'de_DE' => [
		'code'     => 'de',
		'locale'   => 'de_DE',
		'name'     => 'Deutsch',
		'dir'      => 'ltr',
		'flag'     => 'de',
		'facebook' => 'de_DE',
	],
	'de_DE_formal' => [
		'code'     => 'de',
		'locale'   => 'de_DE_formal',
		'name'     => 'Deutsch',
		'dir'      => 'ltr',
		'flag'     => 'de',
		'w3c'      => 'de-DE',
		'facebook' => 'de_DE',
	],
	'dzo' => [
		'code'     => 'dz',
		'locale'   => 'dzo',
		'name'     => 'རྫོང་ཁ',
		'dir'      => 'ltr',
		'flag'     => 'bt',
		'w3c'      => 'dz',
	],
	'el' => [
		'code'     => 'el',
		'locale'   => 'el',
		'name'     => 'Ελληνικά',
		'dir'      => 'ltr',
		'flag'     => 'gr',
		'facebook' => 'el_GR',
	],
	'en_AU' => [
		'code'     => 'en',
		'locale'   => 'en_AU',
		'name'     => 'English',
		'dir'      => 'ltr',
		'flag'     => 'au',
		'facebook' => 'en_US',
	],
	'en_CA' => [
		'code'     => 'en',
		'locale'   => 'en_CA',
		'name'     => 'English',
		'dir'      => 'ltr',
		'flag'     => 'ca',
		'facebook' => 'en_US',
	],
	'en_GB' => [
		'code'     => 'en',
		'locale'   => 'en_GB',
		'name'     => 'English',
		'dir'      => 'ltr',
		'flag'     => 'gb',
		'facebook' => 'en_GB',
	],
	'en_NZ' => [
		'code'     => 'en',
		'locale'   => 'en_NZ',
		'name'     => 'English',
		'dir'      => 'ltr',
		'flag'     => 'nz',
		'facebook' => 'en_US',
	],
	'en_US' => [
		'code'     => 'en',
		'locale'   => 'en_US',
		'name'     => 'English',
		'dir'      => 'ltr',
		'flag'     => 'us',
		'facebook' => 'en_US',
	],
	'en_ZA' => [
		'code'     => 'en',
		'locale'   => 'en_ZA',
		'name'     => 'English',
		'dir'      => 'ltr',
		'flag'     => 'za',
		'facebook' => 'en_US',
	],
	'eo' => [
		'code'     => 'eo',
		'locale'   => 'eo',
		'name'     => 'Esperanto',
		'dir'      => 'ltr',
		'flag'     => 'esperanto',
		'facebook' => 'eo_EO',
	],
	'es_AR' => [
		'code'     => 'es',
		'locale'   => 'es_AR',
		'name'     => 'Español',
		'dir'      => 'ltr',
		'flag'     => 'ar',
		'facebook' => 'es_LA',
	],
	'es_CL' => [
		'code'     => 'es',
		'locale'   => 'es_CL',
		'name'     => 'Español',
		'dir'      => 'ltr',
		'flag'     => 'cl',
		'facebook' => 'es_CL',
	],
	'es_CO' => [
		'code'     => 'es',
		'locale'   => 'es_CO',
		'name'     => 'Español',
		'dir'      => 'ltr',
		'flag'     => 'co',
		'facebook' => 'es_CO',
	],
	'es_CR' => [
		'code'     => 'es',
		'locale'   => 'es_CR',
		'name'     => 'Español',
		'dir'      => 'ltr',
		'flag'     => 'cr',
		'facebook' => 'es_LA',
	],
	'es_ES' => [
		'code'     => 'es',
		'locale'   => 'es_ES',
		'name'     => 'Español',
		'dir'      => 'ltr',
		'flag'     => 'es',
		'facebook' => 'es_ES',
	],
	'es_GT' => [
		'code'     => 'es',
		'locale'   => 'es_GT',
		'name'     => 'Español',
		'dir'      => 'ltr',
		'flag'     => 'gt',
		'facebook' => 'es_LA',
	],
	'es_MX' => [
		'code'     => 'es',
		'locale'   => 'es_MX',
		'name'     => 'Español',
		'dir'      => 'ltr',
		'flag'     => 'mx',
		'facebook' => 'es_MX',
	],
	'es_PE' => [
		'code'     => 'es',
		'locale'   => 'es_PE',
		'name'     => 'Español',
		'dir'      => 'ltr',
		'flag'     => 'pe',
		'facebook' => 'es_LA',
	],
	'es_VE' => [
		'code'     => 'es',
		'locale'   => 'es_VE',
		'name'     => 'Español',
		'dir'      => 'ltr',
		'flag'     => 've',
		'facebook' => 'es_VE',
	],
	'et' => [
		'code'     => 'et',
		'locale'   => 'et',
		'name'     => 'Eesti',
		'dir'      => 'ltr',
		'flag'     => 'ee',
		'facebook' => 'et_EE',
	],
	'eu' => [
		'code'     => 'eu',
		'locale'   => 'eu',
		'name'     => 'Euskara',
		'dir'      => 'ltr',
		'flag'     => 'basque',
		'facebook' => 'eu_ES',
	],
	'fa_AF' => [
		'code'     => 'fa',
		'locale'   => 'fa_AF',
		'name'     => 'فارسی',
		'dir'      => 'rtl',
		'flag'     => 'af',
		'facebook' => 'fa_IR',
	],
	'fa_IR' => [
		'code'     => 'fa',
		'locale'   => 'fa_IR',
		'name'     => 'فارسی',
		'dir'      => 'rtl',
		'flag'     => 'ir',
		'facebook' => 'fa_IR',
	],
	'fi' => [
		'code'     => 'fi',
		'locale'   => 'fi',
		'name'     => 'Suomi',
		'dir'      => 'ltr',
		'flag'     => 'fi',
		'facebook' => 'fi_FI',
	],
	'fo' => [
		'code'     => 'fo',
		'locale'   => 'fo',
		'name'     => 'Føroyskt',
		'dir'      => 'ltr',
		'flag'     => 'fo',
		'facebook' => 'fo_FO',
	],
	'fr_BE' => [
		'code'     => 'fr',
		'locale'   => 'fr_BE',
		'name'     => 'Français',
		'dir'      => 'ltr',
		'flag'     => 'be',
		'facebook' => 'fr_FR',
	],
	'fr_CA' => [
		'code'     => 'fr',
		'locale'   => 'fr_CA',
		'name'     => 'Français',
		'dir'      => 'ltr',
		'flag'     => 'quebec',
		'facebook' => 'fr_CA',
	],
	'fr_FR' => [
		'code'     => 'fr',
		'locale'   => 'fr_FR',
		'name'     => 'Français',
		'dir'      => 'ltr',
		'flag'     => 'fr',
		'facebook' => 'fr_FR',
	],
	'fuc' => [
		'facebook' => 'ff_NG',
	],
	'fur' => [
		'code'     => 'fur',
		'locale'   => 'fur',
		'name'     => 'Furlan',
		'dir'      => 'ltr',
		'flag'     => 'it',
	],
	'fy' => [
		'code'     => 'fy',
		'locale'   => 'fy',
		'name'     => 'Frysk',
		'dir'      => 'ltr',
		'flag'     => 'nl',
		'facebook' => 'fy_NL',
	],
	'ga' => [
		'facebook' => 'ga_IE',
	],
	'gd' => [
		'code'     => 'gd',
		'locale'   => 'gd',
		'name'     => 'Gàidhlig',
		'dir'      => 'ltr',
		'flag'     => 'scotland',
	],
	'gl_ES' => [
		'code'     => 'gl',
		'locale'   => 'gl_ES',
		'name'     => 'Galego',
		'dir'      => 'ltr',
		'flag'     => 'galicia',
		'facebook' => 'gl_ES',
	],
	'gn' => [
		'facebook' => 'gn_PY',
	],
	'gu' => [
		'code'     => 'gu',
		'locale'   => 'gu',
		'name'     => 'ગુજરાતી',
		'dir'      => 'ltr',
		'flag'     => 'in',
		'facebook' => 'gu_IN',
	],
	'hau' => [
		'facebook' => 'ha_NG',
	],
	'haz' => [
		'code'     => 'haz',
		'locale'   => 'haz',
		'name'     => 'هزاره گی',
		'dir'      => 'rtl',
		'flag'     => 'af',
	],
	'he_IL' => [
		'code'     => 'he',
		'locale'   => 'he_IL',
		'name'     => 'עברית',
		'dir'      => 'rtl',
		'flag'     => 'il',
		'facebook' => 'he_IL',
	],
	'hi_IN' => [
		'code'     => 'hi',
		'locale'   => 'hi_IN',
		'name'     => 'हिन्दी',
		'dir'      => 'ltr',
		'flag'     => 'in',
		'facebook' => 'hi_IN',
	],
	'hr' => [
		'code'     => 'hr',
		'locale'   => 'hr',
		'name'     => 'Hrvatski',
		'dir'      => 'ltr',
		'flag'     => 'hr',
		'facebook' => 'hr_HR',
	],
	'hu_HU' => [
		'code'     => 'hu',
		'locale'   => 'hu_HU',
		'name'     => 'Magyar',
		'dir'      => 'ltr',
		'flag'     => 'hu',
		'facebook' => 'hu_HU',
	],
	'hy' => [
		'code'     => 'hy',
		'locale'   => 'hy',
		'name'     => 'Հայերեն',
		'dir'      => 'ltr',
		'flag'     => 'am',
		'facebook' => 'hy_AM',
	],
	'id_ID' => [
		'code'     => 'id',
		'locale'   => 'id_ID',
		'name'     => 'Bahasa Indonesia',
		'dir'      => 'ltr',
		'flag'     => 'id',
		'facebook' => 'id_ID',
	],
	'ido' => [
		'w3c'      => 'io',
	],
	'is_IS' => [
		'code'     => 'is',
		'locale'   => 'is_IS',
		'name'     => 'Íslenska',
		'dir'      => 'ltr',
		'flag'     => 'is',
		'facebook' => 'is_IS',
	],
	'it_IT' => [
		'code'     => 'it',
		'locale'   => 'it_IT',
		'name'     => 'Italiano',
		'dir'      => 'ltr',
		'flag'     => 'it',
		'facebook' => 'it_IT',
	],
	'ja' => [
		'code'     => 'ja',
		'locale'   => 'ja',
		'name'     => '日本語',
		'dir'      => 'ltr',
		'flag'     => 'jp',
		'facebook' => 'ja_JP',
	],
	'jv_ID' => [
		'code'     => 'jv',
		'locale'   => 'jv_ID',
		'name'     => 'Basa Jawa',
		'dir'      => 'ltr',
		'flag'     => 'id',
		'facebook' => 'jv_ID',
	],
	'ka_GE' => [
		'code'     => 'ka',
		'locale'   => 'ka_GE',
		'name'     => 'ქართული',
		'dir'      => 'ltr',
		'flag'     => 'ge',
		'facebook' => 'ka_GE',
	],
	'kab' => [
		'code'     => 'kab',
		'locale'   => 'kab',
		'name'     => 'Taqbaylit',
		'dir'      => 'ltr',
		'flag'     => 'dz',
	],
	'kin' => [
		'w3c'      => 'rw',
		'facebook' => 'rw_RW',
	],
	'kk' => [
		'code'     => 'kk',
		'locale'   => 'kk',
		'name'     => 'Қазақ тілі',
		'dir'      => 'ltr',
		'flag'     => 'kz',
		'facebook' => 'kk_KZ',
	],
	'km' => [
		'code'     => 'km',
		'locale'   => 'km',
		'name'     => 'ភាសាខ្មែរ',
		'dir'      => 'ltr',
		'flag'     => 'kh',
		'facebook' => 'km_KH',
	],
	'kn' => [
		'facebook' => 'kn_IN',
	],
	'ko_KR' => [
		'code'     => 'ko',
		'locale'   => 'ko_KR',
		'name'     => '한국어',
		'dir'      => 'ltr',
		'flag'     => 'kr',
		'facebook' => 'ko_KR',
	],
	'ku' => [
		'facebook' => 'ku_TR',
	],
	'ky_KY' => [
		'facebook' => 'ky_KG',
	],
	'la' => [
		'facebook' => 'la_VA',
	],
	'li' => [
		'facebook' => 'li_NL',
	],
	'lin' => [
		'facebook' => 'ln_CD',
	],
	'lo' => [
		'code'     => 'lo',
		'locale'   => 'lo',
		'name'     => 'ພາສາລາວ',
		'dir'      => 'ltr',
		'flag'     => 'la',
		'facebook' => 'lo_LA',
	],
	'lt_LT' => [
		'code'     => 'lt',
		'locale'   => 'lt_LT',
		'name'     => 'Lietuviškai',
		'dir'      => 'ltr',
		'flag'     => 'lt',
		'facebook' => 'lt_LT',
	],
	'lv' => [
		'code'     => 'lv',
		'locale'   => 'lv',
		'name'     => 'Latviešu valoda',
		'dir'      => 'ltr',
		'flag'     => 'lv',
		'facebook' => 'lv_LV',
	],
	'mg_MG' => [
		'facebook' => 'mg_MG',
	],
	'mk_MK' => [
		'code'     => 'mk',
		'locale'   => 'mk_MK',
		'name'     => 'македонски јазик',
		'dir'      => 'ltr',
		'flag'     => 'mk',
		'facebook' => 'mk_MK',
	],
	'ml_IN' => [
		'code'     => 'ml',
		'locale'   => 'ml_IN',
		'name'     => 'മലയാളം',
		'dir'      => 'ltr',
		'flag'     => 'in',
		'facebook' => 'ml_IN',
	],
	'mlt' => [
		'facebook' => 'mt_MT',
	],
	'mn' => [
		'code'     => 'mn',
		'locale'   => 'mn',
		'name'     => 'Монгол хэл',
		'dir'      => 'ltr',
		'flag'     => 'mn',
		'facebook' => 'mn_MN',
	],
	'mr' => [
		'code'     => 'mr',
		'locale'   => 'mr',
		'name'     => 'मराठी',
		'dir'      => 'ltr',
		'flag'     => 'in',
		'facebook' => 'mr_IN',
	],
	'mri' => [
		'w3c'      => 'mi',
		'facebook' => 'mi_NZ',
	],
	'ms_MY' => [
		'code'     => 'ms',
		'locale'   => 'ms_MY',
		'name'     => 'Bahasa Melayu',
		'dir'      => 'ltr',
		'flag'     => 'my',
		'facebook' => 'ms_MY',
	],
	'my_MM' => [
		'code'     => 'my',
		'locale'   => 'my_MM',
		'name'     => 'ဗမာစာ',
		'dir'      => 'ltr',
		'flag'     => 'mm',
		'facebook' => 'my_MM',
	],
	'nb_NO' => [
		'code'     => 'nb',
		'locale'   => 'nb_NO',
		'name'     => 'Norsk Bokmål',
		'dir'      => 'ltr',
		'flag'     => 'no',
		'facebook' => 'nb_NO',
	],
	'ne_NP' => [
		'code'     => 'ne',
		'locale'   => 'ne_NP',
		'name'     => 'नेपाली',
		'dir'      => 'ltr',
		'flag'     => 'np',
		'facebook' => 'ne_NP',
	],
	'nl_BE' => [
		'code'     => 'nl',
		'locale'   => 'nl_BE',
		'name'     => 'Nederlands',
		'dir'      => 'ltr',
		'flag'     => 'be',
		'facebook' => 'nl_BE',
	],
	'nl_NL' => [
		'code'     => 'nl',
		'locale'   => 'nl_NL',
		'name'     => 'Nederlands',
		'dir'      => 'ltr',
		'flag'     => 'nl',
		'facebook' => 'nl_NL',
	],
	'nl_NL_formal' => [
		'code'     => 'nl',
		'locale'   => 'nl_NL_formal',
		'name'     => 'Nederlands',
		'dir'      => 'ltr',
		'flag'     => 'nl',
		'w3c'      => 'nl-NL',
		'facebook' => 'nl_NL',
	],
	'nn_NO' => [
		'code'     => 'nn',
		'locale'   => 'nn_NO',
		'name'     => 'Norsk Nynorsk',
		'dir'      => 'ltr',
		'flag'     => 'no',
		'facebook' => 'nn_NO',
	],
	'oci' => [
		'code'     => 'oc',
		'locale'   => 'oci',
		'name'     => 'Occitan',
		'dir'      => 'ltr',
		'flag'     => 'occitania',
		'w3c'      => 'oc',
	],
	'ory' => [
		'facebook' => 'or_IN',
	],
	'pa_IN' => [
		'code'     => 'pa',
		'locale'   => 'pa_IN',
		'name'     => 'ਪੰਜਾਬੀ',
		'dir'      => 'ltr',
		'flag'     => 'in',
		'facebook' => 'pa_IN',
	],
	'pl_PL' => [
		'code'     => 'pl',
		'locale'   => 'pl_PL',
		'name'     => 'Polski',
		'dir'      => 'ltr',
		'flag'     => 'pl',
		'facebook' => 'pl_PL',
	],
	'ps' => [
		'code'     => 'ps',
		'locale'   => 'ps',
		'name'     => 'پښتو',
		'dir'      => 'rtl',
		'flag'     => 'af',
		'facebook' => 'ps_AF',
	],
	'pt_BR' => [
		'code'     => 'pt',
		'locale'   => 'pt_BR',
		'name'     => 'Português',
		'dir'      => 'ltr',
		'flag'     => 'br',
		'facebook' => 'pt_BR',
	],
	'pt_PT' => [
		'code'     => 'pt',
		'locale'   => 'pt_PT',
		'name'     => 'Português',
		'dir'      => 'ltr',
		'flag'     => 'pt',
		'facebook' => 'pt_PT',
	],
	'pt_PT_ao90' => [
		'code'     => 'pt',
		'locale'   => 'pt_PT_ao90',
		'name'     => 'Português',
		'dir'      => 'ltr',
		'flag'     => 'pt',
		'facebook' => 'pt_PT',
	],
	'rhg' => [
		'code'     => 'rhg',
		'locale'   => 'rhg',
		'name'     => 'Ruáinga',
		'dir'      => 'ltr',
		'flag'     => 'mm',
	],
	'ro_RO' => [
		'code'     => 'ro',
		'locale'   => 'ro_RO',
		'name'     => 'Română',
		'dir'      => 'ltr',
		'flag'     => 'ro',
		'facebook' => 'ro_RO',
	],
	'roh' => [
		'w3c'      => 'rm',
		'facebook' => 'rm_CH',
	],
	'ru_RU' => [
		'code'     => 'ru',
		'locale'   => 'ru_RU',
		'name'     => 'Русский',
		'dir'      => 'ltr',
		'flag'     => 'ru',
		'facebook' => 'ru_RU',
	],
	'sa_IN' => [
		'facebook' => 'sa_IN',
	],
	'sah' => [
		'code'     => 'sah',
		'locale'   => 'sah',
		'name'     => 'Сахалыы',
		'dir'      => 'ltr',
		'flag'     => 'ru',
	],
	'si_LK' => [
		'code'     => 'si',
		'locale'   => 'si_LK',
		'name'     => 'සිංහල',
		'dir'      => 'ltr',
		'flag'     => 'lk',
		'facebook' => 'si_LK',
	],
	'sk_SK' => [
		'code'     => 'sk',
		'locale'   => 'sk_SK',
		'name'     => 'Slovenčina',
		'dir'      => 'ltr',
		'flag'     => 'sk',
		'facebook' => 'sk_SK',
	],
	'sl_SI' => [
		'code'     => 'sl',
		'locale'   => 'sl_SI',
		'name'     => 'Slovenščina',
		'dir'      => 'ltr',
		'flag'     => 'si',
		'facebook' => 'sl_SI',
	],
	'sna' => [
		'facebook' => 'sn_ZW',
	],
	'so_SO' => [
		'code'     => 'so',
		'locale'   => 'so_SO',
		'name'     => 'Af-Soomaali',
		'dir'      => 'ltr',
		'flag'     => 'so',
		'facebook' => 'so_SO',
	],
	'sq' => [
		'code'     => 'sq',
		'locale'   => 'sq',
		'name'     => 'Shqip',
		'dir'      => 'ltr',
		'flag'     => 'al',
		'facebook' => 'sq_AL',
	],
	'sr_RS' => [
		'code'     => 'sr',
		'locale'   => 'sr_RS',
		'name'     => 'Српски језик',
		'dir'      => 'ltr',
		'flag'     => 'rs',
		'facebook' => 'sr_RS',
	],
	'srd' => [
		'w3c'      => 'sc',
		'facebook' => 'sc_IT',
	],
	'su_ID' => [
		'code'     => 'su',
		'locale'   => 'su_ID',
		'name'     => 'Basa Sunda',
		'dir'      => 'ltr',
		'flag'     => 'id',
	],
	'sv_SE' => [
		'code'     => 'sv',
		'locale'   => 'sv_SE',
		'name'     => 'Svenska',
		'dir'      => 'ltr',
		'flag'     => 'se',
		'facebook' => 'sv_SE',
	],
	'sw' => [
		'facebook' => 'sw_KE',
	],
	'syr' => [
		'facebook' => 'sy_SY',
	],
	'szl' => [
		'code'     => 'szl',
		'locale'   => 'szl',
		'name'     => 'Ślōnskŏ gŏdka',
		'dir'      => 'ltr',
		'flag'     => 'pl',
		'facebook' => 'sz_PL',
	],
	'ta_IN' => [
		'code'     => 'ta',
		'locale'   => 'ta_IN',
		'name'     => 'தமிழ்',
		'dir'      => 'ltr',
		'flag'     => 'in',
		'facebook' => 'ta_IN',
	],
	'ta_LK' => [
		'code'     => 'ta',
		'locale'   => 'ta_LK',
		'name'     => 'தமிழ்',
		'dir'      => 'ltr',
		'flag'     => 'lk',
		'facebook' => 'ta_IN',
	],
	'tah' => [
		'code'     => 'ty',
		'locale'   => 'tah',
		'name'     => 'Reo Tahiti',
		'dir'      => 'ltr',
		'flag'     => 'pf',
	],
	'te' => [
		'code'     => 'te',
		'locale'   => 'te',
		'name'     => 'తెలుగు',
		'dir'      => 'ltr',
		'flag'     => 'in',
		'facebook' => 'te_IN',
	],
	'tg' => [
		'facebook' => 'tg_TJ',
	],
	'th' => [
		'code'     => 'th',
		'locale'   => 'th',
		'name'     => 'ไทย',
		'dir'      => 'ltr',
		'flag'     => 'th',
		'facebook' => 'th_TH',
	],
	'tl' => [
		'code'     => 'tl',
		'locale'   => 'tl',
		'name'     => 'Tagalog',
		'dir'      => 'ltr',
		'flag'     => 'ph',
		'facebook' => 'tl_PH',
	],
	'tr_TR' => [
		'code'     => 'tr',
		'locale'   => 'tr_TR',
		'name'     => 'Türkçe',
		'dir'      => 'ltr',
		'flag'     => 'tr',
		'facebook' => 'tr_TR',
	],
	'tt_RU' => [
		'code'     => 'tt',
		'locale'   => 'tt_RU',
		'name'     => 'Татар теле',
		'dir'      => 'ltr',
		'flag'     => 'ru',
		'facebook' => 'tt_RU',
	],
	'tuk' => [
		'w3c'      => 'tk',
		'facebook' => 'tk_TM',
	],
	'tzm' => [
		'facebook' => 'tz_MA',
	],
	'ug_CN' => [
		'code'     => 'ug',
		'locale'   => 'ug_CN',
		'name'     => 'Uyƣurqə',
		'dir'      => 'ltr',
		'flag'     => 'cn',
	],
	'uk' => [
		'code'     => 'uk',
		'locale'   => 'uk',
		'name'     => 'Українська',
		'dir'      => 'ltr',
		'flag'     => 'ua',
		'facebook' => 'uk_UA',
	],
	'ur' => [
		'code'     => 'ur',
		'locale'   => 'ur',
		'name'     => 'اردو',
		'dir'      => 'rtl',
		'flag'     => 'pk',
		'facebook' => 'ur_PK',
	],
	'uz_UZ' => [
		'code'     => 'uz',
		'locale'   => 'uz_UZ',
		'name'     => 'Oʻzbek',
		'dir'      => 'ltr',
		'flag'     => 'uz',
		'facebook' => 'uz_UZ',
	],
	'vec' => [
		'code'     => 'vec',
		'locale'   => 'vec',
		'name'     => 'Vèneto',
		'dir'      => 'ltr',
		'flag'     => 'veneto',
	],
	'vi' => [
		'code'     => 'vi',
		'locale'   => 'vi',
		'name'     => 'Tiếng Việt',
		'dir'      => 'ltr',
		'flag'     => 'vn',
		'facebook' => 'vi_VN',
	],
	'xho' => [
		'facebook' => 'xh_ZA',
	],
	'yor' => [
		'facebook' => 'yo_NG',
	],
	'zh_CN' => [
		'code'     => 'zh',
		'locale'   => 'zh_CN',
		'name'     => '中文 (中国)',
		'dir'      => 'ltr',
		'flag'     => 'cn',
		'facebook' => 'zh_CN',
	],
	'zh_HK' => [
		'code'     => 'zh',
		'locale'   => 'zh_HK',
		'name'     => '中文 (香港)',
		'dir'      => 'ltr',
		'flag'     => 'hk',
		'facebook' => 'zh_HK',
	],
	'zh_TW' => [
		'code'     => 'zh',
		'locale'   => 'zh_TW',
		'name'     => '中文 (台灣)',
		'dir'      => 'ltr',
		'flag'     => 'tw',
		'facebook' => 'zh_TW',
	],
];
